[package]
name = "terminal_rpg"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
dirs = "5"
base64 = "0.22"
uuid = { version = "1", features = ["v4"] }
chrono = "0.4"
rand = "0.8.5"

