[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
crossterm = "0.28"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
dirs = "5"
base64 = "0.22"

